task_manager/label/urls.py
from django.urls import path
from task_manager.label import views

urlpatterns = [
    path('<int:pk>/update/', views.LabelUpdateView.as_view(), name='label_update'),
    path('<int:pk>/delete/', views.LabelDeleteView.as_view(), name='label_delete'),
    path('create/', views.LabelCreateView.as_view()),
    path('', views.LabelView.as_view(), name='labels'),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

from task_manager import views
from task_manager.user import views as login_views

urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('users/', include('task_manager.user.urls')),
    path('statuses/', include('task_manager.status.urls')),
    path('labels/', include('task_manager.label.urls')),
    path('tasks/', include('task_manager.task.urls')),
    path('login/', login_views.UsersLoginView.as_view(), name='login'),
    path('logout/', login_views.UsersLogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
]

handler404 = 'task_manager.views.error_404'

task_manager/label/models.py
from django.db import models


class Label(models.Model):

    name = models.CharField(max_length=200, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

task_manager/label/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Label


class LabelForm(forms.ModelForm):
    class Meta:
        model = Label
        fields = ('name', )
        labels = {
            'name': _('Status Name'),
        }

task_manager/label/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.translation import gettext as _
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.urls import reverse_lazy

from .forms import LabelForm
from .models import Label
from task_manager.mixins import DeleteErrorMixin


# ALL LABELS page
class LabelView(LoginRequiredMixin, ListView):
    model = Label
    template_name = 'labels/labels.html'
    ordering = ['id']


# CREATE LABEL page
class LabelCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Label
    form_class = LabelForm
    template_name = 'labels/new_label.html'
    success_url = reverse_lazy('labels')
    success_message = _('The label has been created')


# UPDATE LABEL page
class LabelUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Label
    form_class = LabelForm
    template_name = 'labels/update_label.html'
    success_url = reverse_lazy('labels')
    success_message = _('The label has been updated')


# DELETE STATUS page
class LabelDeleteView(SuccessMessageMixin, LoginRequiredMixin, DeleteErrorMixin, DeleteView):
    model = Label
    template_name = 'labels/delete_label.html'
    success_url = reverse_lazy('labels')
    success_message = _('The label has been deleted')
    reject_message = _('You cannot delete the label that is used in a task')

templates/labels/delete_label.html
{% extends '../layout.html' %}
{% load bootstrap5 i18n %}
{% block content %}

<h1 class="my-4">{% translate 'Label deletion' %}</h1>
<p> {% translate 'Are you certain you want to delete the label' %} '{{ label.name }}' ?</p>
<form action="{% url 'label_delete' label.id %}" method="post">
  {% csrf_token %}
  <input class="btn btn-danger" type="submit" value="{% translate 'Yes, I am' %}">
</form>

{% endblock content %}

templates/labels/labels.html
{% extends '../layout.html' %}
{% load bootstrap5 i18n %}
{% block content %}

<h1 class="my-4">{% translate 'Labels' %}</h1>
<a class="nav-link" href="/labels/create/">{% translate 'Create label' %}</a>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>{% translate 'Label Name' %}</th>
      <th>{% translate 'Created at' %}</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for label in label_list %}
    <tr>
      <td>{{ label.id }}</td>
      <td>{{ label.name }}</td>
      <td>{{ label.created_at }}</td>
      <td>
        <a href="{% url 'label_update' pk=label.id %}">{% translate 'Edit' %}</a>
        <br>
        <a href="{% url 'label_delete' pk=label.id %}">{% translate 'Delete' %}</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock content %}

templates/labels/new_label.html
{% extends '../layout.html' %}
{% load bootstrap5 i18n %}
{% block content %}

<h1 class="my-4">{% translate 'Create label' %}</h1>
<form method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input class="btn btn-primary" type="submit" value="{% translate 'Create' %}">
</form>

{% endblock content %}

templates/labels/update_label.html
{% extends '../layout.html' %}
{% load bootstrap5 i18n %}
{% block content %}

<h1 class="my-4">{% translate 'Update label' %}</h1>
<form method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input class="btn btn-primary" type="submit" value="{% translate 'Update' %}">
</form>

{% endblock content %}