task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

from task_manager import views
from task_manager.user import views as login_views

urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('users/', include('task_manager.user.urls')),
    path('statuses/', include('task_manager.status.urls')),
    path('labels/', include('task_manager.label.urls')),
    path('tasks/', include('task_manager.task.urls')),
    path('login/', login_views.UsersLoginView.as_view(), name='login'),
    path('logout/', login_views.UsersLogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
]

handler404 = 'task_manager.views.error_404'

task_manager/user/urls.py
from django.urls import path

from task_manager.user import views

urlpatterns = [
    path('<int:pk>/update/', views.UsersUpdateView.as_view(), name='user_update'),
    path('<int:pk>/delete/', views.UsersDeleteView.as_view(), name='user_delete'),
    path('create/', views.UsersCreateFormView.as_view()),
    path('', views.UsersView.as_view(), name='users'),
]

task_manager/user/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    def __str__(self):
        return f'{self.first_name} {self.last_name}'

task_manager/user/forms.py
from django.contrib.auth.forms import UserCreationForm, forms
from django.utils.translation import gettext_lazy as _

from .models import User


class UserSignUpForm(UserCreationForm):
    first_name = forms.CharField(required=True, label=_('First name'))
    last_name = forms.CharField(required=True, label=_('Last name'))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username')


class UserUpdateForm(UserSignUpForm):

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if self.instance.username == username:
            return username
        return super().clean_username()

task_manager/user/views.py
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from .forms import UserSignUpForm, UserUpdateForm
from .models import User
from task_manager.mixins import (NeedAuthMixin, NeedPermitMixin, FeedbackMixin,
                                 DeleteErrorMixin, HandleNoPermissionMixin)


# ALL USERS page
class UsersView(ListView):
    model = User
    template_name = 'users/users.html'
    ordering = ['id']


# CREATE USER page
class UsersCreateFormView(SuccessMessageMixin, CreateView):
    model = User
    form_class = UserSignUpForm
    success_url = reverse_lazy('login')
    template_name = 'users/new_user.html'
    success_message = _('The user has been registered')


# UPDATE USER page
class UsersUpdateView(SuccessMessageMixin, HandleNoPermissionMixin,
                      NeedAuthMixin, NeedPermitMixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'users/update_user.html'
    login_url = reverse_lazy('login')
    unauthorized_url = reverse_lazy('users')
    success_url = reverse_lazy('users')
    success_message = _('The user has been updated')


# DELETE USER page
class UsersDeleteView(SuccessMessageMixin, HandleNoPermissionMixin, NeedAuthMixin,
                      NeedPermitMixin, DeleteErrorMixin, DeleteView):
    model = User
    template_name = 'users/delete_user.html'
    login_url = reverse_lazy('login')
    success_url = reverse_lazy('users')
    success_message = _('The user has been deleted')
    reject_message = _('You cannot delete the user that is ascribed a task')


# LOGIN USER page
class UsersLoginView(FeedbackMixin, LoginView):
    model = User
    form_class = AuthenticationForm
    redirect_authenticated_user = True
    template_name = 'login.html'
    next_page = reverse_lazy('home')
    success_message = _('You have logged in')
    error_message = _('Enter correct username and password. Both fields can be case-sensitive')


# LOGOUT USER page
class UsersLogoutView(LogoutView):
    next_page = reverse_lazy('home')
    success_message = _('You have logged out')

    def dispatch(self, request, *args, **kwargs):
        messages.add_message(request, messages.INFO, self.success_message)
        return super().dispatch(request, *args, **kwargs)

templates/users/delete.html
<!DOCTYPE html>
{% load i18n %}
<html>
{% include "head.html" %}
<body class="d-flex flex-column min-vh-100">
{% include "navigation.html" %}
  <div class="container wrapper flex-grow-1">

    <h1 class="my-4">Удаление пользователя</h1>
    <p>Вы уверены, что хотите удалить {{ fullname }} ?</p>
    <form action="{% url 'user_delete' user_id %}" method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="Да, удалить">
    </form>

  </div>
{% include "footer.html" %}
</body>
</html>

templates/users/delete_user.html
{% extends '../layout.html' %}
{% load bootstrap5 i18n %}
{% block content %}

<h1 class="my-4">{% translate 'User deletion' %}</h1>
<p>{% translate 'Are you certain you want to delete' %} {{ user.first_name}} {{ user.last_name}}?</p>
<form action="{% url 'user_delete' user.id %}" method="post">
  {% csrf_token %}
  <input class="btn btn-danger" type="submit" value="{% translate 'Yes, I am' %}">
</form>

{% endblock content %}

templates/users/new_user.html
{% extends '../layout.html' %}
{% load bootstrap5 i18n %}
{% block content %}
    <h1 class="my-4">{% translate 'Registration' %}</h1>

    <form class="text-left" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input role="button" class="btn btn-primary" type="submit" value="{% translate 'Register' %}" >
    </form>

{% endblock content %}

templates/users/update.html
<!DOCTYPE html>
{% load i18n %}
<html>
{% include "head.html" %}
<body class="d-flex flex-column min-vh-100">
{% include "navigation.html" %}

  <div class="container wrapper flex-grow-1">
    <h1 class="my-4">Изменение пользователя</h1>
    <form method="post">
      {% csrf_token %}

      <div class="form-group">
        {{ form.first_name.label_tag }}
        {{ form.first_name }}
        <small class="form-text text-muted">Обязательное поле. Не более 150 символов. Только буквы, цифры и символы @/./+/-/_.
        </small>
      </div>
      <div class="form-group">
        {{ form.last_name.label_tag }}
        {{ form.last_name }}
      </div>
      <div class="form-group">
        {{ form.username.label_tag }}
        {{ form.username }}
      </div>
      <div class="form-group">
        {{ form.password.label_tag }}
        {{ form.password }}
        <small class="form-text text-muted">
          <ul>
            <li>Ваш пароль должен содержать как минимум 3 символа.</li>
          </ul>
        </small>
      </div>
      <div class="form-group">
        {{ form.password_confirmation.label_tag }}
        {{ form.password_confirmation }}
        <small class="form-text text-muted">Для подтверждения введите, пожалуйста, пароль ещё раз.</small>
      </div>
      <div class="form-group">
        <input class="btn btn-primary" type="submit" value="Изменить">
      </div>
    </form>
  </div>

{% include "footer.html" %}
</body>
</html>

templates/users/update_user.html
{% extends '../layout.html' %}
{% load bootstrap5 i18n %}
{% block content %}

<h1 class="my-4">{% translate 'Update user' %}</h1>

<form class="text-left" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input role="button" class="btn btn-primary" type="submit" value="{% translate 'Update' %}" >
</form>
{% endblock content %}

templates/users/users.html
{% extends '../layout.html' %}
{% load bootstrap5 i18n %}
{% block content %}

<h1 class="my-4">{% translate 'Users' %}</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>{% translate 'Username' %}</th>
      <th>{% translate 'Full name' %}</th>
      <th>{% translate 'Created at' %}</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for user in user_list %}
    <tr>
      <td>{{ user.id }}</td>
      <td>{{ user.username }}</td>
      <td>{{ user.first_name }} {{ user.last_name }}</td>
      <td>{{ user.date_joined }}</td>
      <td>
        <a href="{% url 'user_update' user.id %}">{% translate 'Edit' %}</a>
        <br>
        <a href="{% url 'user_delete' user.id %}">{% translate 'Delete' %}</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock content %}